Added a lot more stuff to nfs suite
Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/suites/nfs b/suites/nfs
--- a/suites/nfs
+++ b/suites/nfs
@@ -76,6 +76,9 @@ function server_write_exports {
 
 	echo "exports file now:"
 	testbus_download_file $NFS_SERVER /etc/exports -
+
+	echo "visible on client side:"
+	run_client /usr/sbin/showmount -e $NFS_SERVER_IP
 }
 
 ##################################################################
@@ -131,6 +134,8 @@ EOF
 
 server_update_hosts "$NFS_CLIENT_IP	$NFS_CLIENT_NAME nfs-client.testbus.opensuse.org"
 
+testbus_trace "Befor next test-begin"
+
 ##################################################################
 # Initialize NFS server
 ##################################################################
@@ -148,35 +153,87 @@ testbus_test_success
 ##################################################################
 testbus_group_begin mount-tests
 
-testbus_test_begin byname
-run_client /bin/mount $NFS_SERVER_NAME:/srv/nfs/dir1 /mnt/nfs1
-run_client /bin/umount /mnt/nfs1
+function mount_should_succeed {
 
-testbus_test_begin byaddr
-run_client /bin/mount $NFS_SERVER_IP:/srv/nfs/dir1 /mnt/nfs1
-run_client /bin/umount /mnt/nfs1
-
-function mount_should_fail {
+	local testname server_dir client_dir options
 
 	testname=$1
 	server_dir=$2
 	client_dir=$3
+	shift 3
+
+	options=
+	if [ -n "$*" ]; then
+		options="-o $*"
+	fi
 
 	testbus_test_begin $testname
-	if __run_client /bin/mount $NFS_SERVER_IP:$server_dir $client_dir; then
-		testbus_test_failure "This mount attempt should have failed"
-		umount $client_dir
+	if __run_client /bin/mount $NFS_SERVER_IP:$server_dir $client_dir $options; then
+		if ! __run_client /bin/grep " $client_dir" /proc/mounts; then
+			testbus_test_failure "Directory was not mounted (which is bad), but mount(8) reported success (which is even worse)"
+		else
+			testbus_test_success
+		fi
 	else
-		testbus_test_success
+		if __run_client /bin/grep " $client_dir" /proc/mounts; then
+			testbus_test_failure "Directory was mounted (which is good), but mount(8) reported an error"
+		else
+			testbus_test_failure "This mount attempt should have succeeded"
+		fi
 	fi
+	run_client /bin/umount $client_dir
 }
 
-mount_should_fail non-exported /srv/nfs/dir4 /mnt/nfs4
+function mount_should_fail {
+
+	local testname server_dir client_dir options
+
+	testname=$1
+	server_dir=$2
+	client_dir=$3
+	shift 3
+
+	options=
+	if [ -n "$*" ]; then
+		options="-o $*"
+	fi
+
+	testbus_test_begin $testname
+	if __run_client /bin/mount $NFS_SERVER_IP:$server_dir $client_dir $options; then
+		if ! __run_client /bin/grep " $client_dir" /proc/mounts; then
+			testbus_test_failure "Directory was not mounted (which is good), but mount(8) reported success"
+		else
+			testbus_test_failure "This mount attempt should have failed"
+		fi
+	else
+		if __run_client /bin/grep " $client_dir" /proc/mounts; then
+			testbus_test_failure "Directory was mounted (which is bad), even though mount(8) reported an error"
+		else
+			testbus_test_success
+		fi
+	fi
+	run_client /bin/umount $client_dir
+}
+
+testbus_test_begin byname
+run_client /bin/mount $NFS_SERVER_NAME:/srv/nfs/dir1 /mnt/nfs1
+run_client /bin/umount /mnt/nfs1
+
+mount_should_succeed byaddr		/srv/nfs/dir1	/mnt/nfs1
+mount_should_succeed nfsv2		/srv/nfs/dir1	/mnt/nfs1 vers=2
+mount_should_succeed nfsvers2		/srv/nfs/dir1	/mnt/nfs1 nfsvers=2
+mount_should_succeed nfsvers3		/srv/nfs/dir1	/mnt/nfs1 nfsvers=3
+mount_should_succeed nfsvers2-nolock	/srv/nfs/dir1	/mnt/nfs1 nfsvers=2,nolock
+mount_should_succeed nfsvers3-nolock	/srv/nfs/dir1	/mnt/nfs1 nfsvers=3,nolock
+
+testbus_group_begin non-exported
+mount_should_fail unexported		/srv/nfs/dir4	/mnt/nfs4
 
 # These are "exported" for the NFSv4 virtual file handle space,
 # but should these really be available to NFSv2/v3 clients as well?
-mount_should_fail non-exported /srv/nfs /mnt/nfs4
-mount_should_fail non-exported /srv /mnt/nfs4
+mount_should_fail nfsv4-fhspace1	/srv/nfs	/mnt/nfs4
+mount_should_fail nfsv4-fhspace2	/srv		/mnt/nfs4
+testbus_group_finish SUCCESS
 
 testbus_group_finish SUCCESS
 
@@ -317,5 +374,114 @@ EOF
 nfs_test_rootsquash /srv/nfs/dir1 /mnt/nfs1 60000
 
 testbus_group_finish SUCCESS
+
+##################################################################
+# Exercise the NFS protocol
+##################################################################
+function nfs_test_writefile {
+
+	dir=$1; shift
+	tf=$dir/testfile
+
+	testbus_test_begin writefile
+	run_client /bin/dd if=/dev/zero of=$tf bs=1k count=4k
+	run_client /bin/rm -f $tf
+	testbus_test_success
+}
+
+function nfs_test_chown {
+
+	dir=$1; shift
+	tf=$dir/testfile
+
+	testbus_test_begin chown
+	run_client /bin/touch $tf
+	run_client /bin/chown --changes nobody $tf
+	run_client /bin/rm -f $tf
+	testbus_test_success
+}
+
+function nfs_test_chmod {
+
+	dir=$1; shift
+	tf=$dir/testfile
+
+	testbus_test_begin chmod
+	run_client /bin/touch $tf
+	run_client /bin/chmod --changes 0600 $tf
+	run_client /bin/rm -f $tf
+	testbus_test_success
+}
+
+function nfs_test_sillyrename {
+
+	dir=$1; shift
+	tf=$dir/testfile
+
+	testbus_test_begin sillyrename
+	run_client --send-script - $tf <<"EOF"
+#!/bin/bash
+
+tf=$1
+echo frankzappa >$tf
+
+{
+	rm -f $tf || exit 1
+
+	input=`cat`
+	if [ "$input" != "frankzappa" ]; then
+		echo "Tried to read from deleted file, but failed"
+		exit 1
+	fi
+	exit 0
+} <$tf
+
+EOF
+	testbus_test_success
+}
+
+function nfs_test_allfunc {
+
+	options="$@"
+
+	server_dir=/srv/nfs/dir1
+	client_dir=/mnt/nfs1
+
+	if run_client /bin/mount $NFS_SERVER_NAME:$server_dir $client_dir -o $options; then
+		nfs_test_writefile $client_dir
+		nfs_test_chown $client_dir
+		nfs_test_chmod $client_dir
+		nfs_test_sillyrename $client_dir
+		run_client /bin/umount $client_dir
+	else
+		echo "Skipping NFS tests for this set of options" >&2
+	fi
+}
+
+server_write_exports - <<EOF
+/srv/nfs/dir1	*(rw,no_root_squash)
+EOF
+
+##################################################################
+# Test NFSv2
+##################################################################
+testbus_group_begin nfsv2
+nfs_test_allfunc vers=2,nolock
+testbus_group_finish SUCCESS
+
+##################################################################
+# Test NFSv3
+##################################################################
+testbus_group_begin nfsv3
+nfs_test_allfunc vers=3,nolock
+testbus_group_finish SUCCESS
+
+##################################################################
+# Test NFSv4
+##################################################################
+testbus_group_begin nfsv4
+nfs_test_allfunc vers=4
+testbus_group_finish SUCCESS
+
 
 testbus_exit
